
module.exports = {
  // cc: {
  //   name: "Characters Chest",
  //   description: "Allows you to participate in raid battles.",
  //   emoji: "<:raid_ticket:1458395626772627643>",
  //   type: "Consumable",
  //   currency: "gold",
  // },
  rt: {
    name: "Raid Ticket",
    description: "Allows you to participate in raid battles.",
    emoji: "<:raid_ticket:1458395626772627643>",
    type: "Consumable",
    price : 25000,
    currency: "gold",
  },
  c5: {
    name: "Premium Character Chest",
    description: "Unlocks a random 5-Star character from the global roster.",
    emoji: "<:chest_5:1457265255553040529>",
    type: "Consumable",
    price: 440,
    currency: "gem",
  },
  b1: {
    name: "Minor Blessing",
    description: "Grants **1,800 XP** for a card.",
    emoji: "✨",
    type: "Consumable",
    price: 500,
    currency: "gold",
    xpAmount: 1800,
  },

  b2: {
    name: "Major Blessing",
    description: "Grants **18,000 XP** for a card.",
    emoji: "🌟",
    type: "Consumable",
    price: 4500,
    currency: "gold",
    xpAmount: 18000,
  },

  b3: {
    name: "Grand Blessing",
    description: "Grants **90,000 XP** for a card.",
    emoji: "💫",
    type: "Consumable",
    price: 20000,
    currency: "gold",
    xpAmount: 90000,
  },

  b4: {
    name: "Divine Blessing",
    description: "Grants **450,000 XP** for a card.",
    emoji: "💠",
    type: "Consumable",
    price: 90000,
    currency: "gold",
    xpAmount: 450000,
  },


  // --- Gacha Items ---
  ticket: {
    name: "Summon Ticket",
    description: "Used to pull on standard and featured banner.",
    emoji: "🎫",
    type: "Gacha",
    price: 8,
    currency: "gem",
  },
  tide: {
    name: "Radiant Tide",
    description: "Used to convene for Resonators.",
    emoji: "<:wuwaPull:1453226896329412770>",
    type: "Gacha",
    price: 8,
    currency: "gem",
  },
  tape: {
    name: "Encrypted Master Tape",
    description: "Used for Signal Search.",
    emoji: "<:zzzPull:1453233952151310478>",
    type: "Gacha",
    price: 8,
    currency: "gem",
  },
  fate: {
    name: "Intertwined Fate",
    description: "Used to Wish.",
    emoji: "<:genshinPull:1453234890416984207>",
    type: "Gacha",
    price: 8,
    currency: "gem",
  },
  pass: {
    name: "Special Pass",
    description: "Used to Warp.",
    emoji: "<:hsrPull:1453226721632587849>",
    type: "Gacha",
    price: 8,
    currency: "gem",
  },
  permit: {
    name: "Headhunting Permit",
    description: "Used to recuit Operators.",
    emoji: "<:permit:1454862332374155366>",
    type: "Gacha",
    price: 8,
    currency: "gem",
  },
};
